# Generated by Django 4.2.6 on 2023-10-09 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_category_ingredient_crafted_from_recipe_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
