# Generated by Django 4.2.6 on 2023-10-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_category_parent_category_ingredient_crafted_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
